# root level
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env       
    networks:
      - app-network
    ports:
      - "8092:8092"

  db:
    image: postgres:15
    restart: always
    container_name: postgres-container
    env_file:
      - .env 
    ports:
    - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    depends_on:
     - backend
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://localhost:8092   
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
